services:
  core:
    container_name: novumquay-data-engineering
    image: novumquay-data-engineering
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Exposes the application port
      - "8080:8080"
      # Exposes the traditional VNC port (for VNC clients)
      - "5901:5901"
      # Exposes the noVNC web port (for browser access)
      - "6901:6901"
    networks:
      - novumquay-network

networks:
  novumquay-network:
    external: true
